### PR TITLE
Fix conditional logic

### PR DESCRIPTION
**Pull request by MatthewMi11er**
Unless I'm missing something `ansible_ssh_user | bool` will (always?) evaluate to `False`, using `is defined` seems better.

### CODE REVIEW

**Comment by MatthewMi11er** [comment]
Several other Debops roles use this same logic.

**Comment by drybjed** [comment]
If `ansible_ssh_user` is not explicitly defined, in Ansible 2.0 it returns `none`, which should be interpreted as `False`. Although I'm not sure... I guess it needs some testing of different scenarios. I'll check it out shortly.

**Comment by MatthewMi11er** [comment]
In my testing on Ansible 1.9.4 when `ansible_ssh_user` is explicitly defined, casting to a `bool` returns `false`

**Comment by drybjed** [comment]
You're right @MatthewMi11er, `|bool` looks specify for True/False strings, or empty strings/lists. I'm not sure yet how `var | is defined` works with `none`, I'll need to check that.

**Comment by MatthewMi11er** [comment]
@drybjed I think Ansible may just be setting the `ansible_ssh_user` to a python `None` internally, so would `ansible_ssh_user != None` work?

**Pull request closed without merging**
