### PR TITLE
Generate a ssh key for root by default.

### PR DESCRIPTION
**Pull request by bfabio**

### CODE REVIEW

**Comment by drybjed** [comment]
Can you give any reasoning for this? I can see some potential usefulness in this, but I wonder what's your take on it.

I suppose that creating a separate `debops.root_account` role and consolidating `root` management from `debops.users` and `debops.console` there might be in order...

**Comment by bfabio** [comment]
I need the root key in another role, but I think it's just a reasonable default to have for every debops host.

Even if it's not used, it would be just there, doing no harm. There's no downside I can think of.

**Comment by drybjed** [comment]
Fair enough, but I would still move this to a separate root management role, and have a configurable key size, at least. I will look into it in some spare time.

**Comment by bfabio** [comment]
Obsoleted by https://github.com/debops/ansible-root_account

**Pull request closed without merging**
