### PR TITLE
Allow to set default shell.

### PR DESCRIPTION
**Pull request by ypid**
The might be other ways to achieve this for example setting it in `/etc/default/useradd`.

### CODE REVIEW

**Comment by patrickheeney** [comment]
This looks to be the same as #27

**Comment by ypid** [comment]
Should have checked that …

**Comment by drybjed** [comment]
Beware of unintended consequences. :-) I guess this could be implemented like this, in defaults:
```
users_default_shell: ''
```
And in tasks:
```
- user:
    name: '{{ item.name }}'
    shell: '{{ item.shell | d(users_default_shell if users_default_shell|bool else omit) }}'
```
In Ansible v2 the default() function is activated only when variables are undefined, and I don't like undefined variables in roles because they are thus undocumented.

Changing the default in `/etc/default/useradd` is a nice idea, but I'm not sure if for example setting default as `/bin/zsh` would affect installation of packages or automatically created user accounts.

**Comment by ypid** [comment]
> but I'm not sure if for example setting default as /bin/zsh would affect installation of packages or automatically created user accounts.

That could be problematic. I also have not tested it. So I will not use a global default shell (`users_default_shell` then …

**Pull request closed without merging**
