### PR TITLE
removed superfluous bracket

### PR DESCRIPTION
**Pull request by smcavoy-travelbird**
as in title.

### CODE REVIEW

**Comment by drybjed** [comment]
Thanks for the fix! :-)

**Comment by smcavoy-travelbird** [comment]
any idea when this will be updated on galaxy?


Thanks,


Sean

**Comment by drybjed** [comment]
I'll tag the new release in a few minutes.

**Comment by smcavoy-travelbird** [comment]
Thanks!

On Tue, Jan 5, 2016 at 1:52 PM, Maciej Delmanowski <notifications@github.com

**Comment by drybjed** [comment]
@smcavoy-travelbird And done.

**Pull request merged**
