### PR TITLE
Added users_default_home_mode to set a default mode for home_mode.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by drybjed** [comment]
I don't like to have commented out defaults... Perhaps better way would be to set an umask value for new user home directories in `/etc/login.defs`... Hey, wait a second...

https://github.com/debops/ansible-auth/blob/master/tasks/login_passwd_shadow.yml#L3-L9

https://github.com/debops/ansible-auth/blob/master/defaults/main.yml#L44-L45

**Comment by ypid** [comment]
I know /etc/login.defs and umask. The problem is that when I install a workstation it creates a default user during installation and the later changed umask value does not change the home permissions on disk or am I missing something? Maybe it could be combined with the auth role, not sure.

**Comment by drybjed** [comment]
How do you create the default account, via preseeding or bootstrap? My preseeding account home directories have 0750 permissions by default.

**Comment by ypid** [comment]
Have not looked into your preseeding role to deep but it is nice to hear that you thought about that. Nowadays I use the bootstrap role.

**Comment by drybjed** [comment]
So, here's the [bootstrap home mode](https://github.com/debops/ansible-auth/blob/master/defaults/main.yml#L44-L45) and [task which enforce permissions](https://github.com/debops/ansible-bootstrap/blob/master/tasks/main.yml#L92-L108) among other things. Perhaps try creating a new host and after bootstraping check the home directory mode?

**Comment by ypid** [comment]
Hm. OK looks good. I actually recognized it for my local workstation which is also managed by Ansible but OK, this seems to be handled on multiple other places already so I can just configure it for all users …

**Comment by drybjed** [comment]
Actually if you run bootstrap on your workstation (remember to set correct home dir/account mode), it will probably set permissions to 0750.

**Comment by ypid** [comment]
Good idea but currently the tasks in question are skipped because of https://github.com/debops/ansible-bootstrap/blob/95e49cfcb27266a54bc293d00114e5c816b13ea0/tasks/main.yml#L41-L44.

**Comment by drybjed** [comment]
@ypid I see... Then perhaps adding a variable to override that from inventory would be a better idea, something like `bootstrap_admin_manage_existing`, maybe? In preseed / LXC / OpenVZ template that's not really an issue because account most likely won't exist, but in bootstrap it might be useful.

**Comment by ypid** [comment]
Sounds good. I can do that later today.

**Pull request closed without merging**
